
[[constraint]]
  name = "github.com/PuerkitoBio/purell"
  revision = "8a290539e2e8629dbc4e6bad948158f790ec31f4"

[[constraint]]
  name = "github.com/PuerkitoBio/urlesc"
  revision = "5bd2802263f21d8788851d5305584c82a5c75d7e"

[[constraint]]
  name = "github.com/emicklei/go-restful"
  revision = "ff4f55a206334ef123e4f79bbf348980da81ca46"

[[constraint]]
  name = "github.com/go-openapi/jsonpointer"
  revision = "46af16f9f7b149af66e5d1bd010e3574dc06de98"

[[constraint]]
  name = "github.com/go-openapi/jsonreference"
  revision = "13c6e3589ad90f49bd3e3bbe2c2cb3d7a4142272"

[[constraint]]
  name = "github.com/go-openapi/spec"
  revision = "6aced65f8501fe1217321abf0749d354824ba2ff"

[[constraint]]
  name = "github.com/go-openapi/swag"
  revision = "1d0bd113de87027671077d3c71eb3ac5d7dbba72"

[[constraint]]
  name = "github.com/gogo/protobuf"
  revision = "c0656edd0d9eab7c66d1eb0c568f9039345796f7"

[[constraint]]
  name = "github.com/golang/glog"
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"

[[constraint]]
  name = "github.com/mailru/easyjson"
  revision = "d5b7844b561a7bc640052f1b935f7b800330d7e0"

[[constraint]]
  name = "github.com/spf13/pflag"
  revision = "9ff6c6923cfffbcd502984b8e0c80539a94968b7"

[[constraint]]
  name = "golang.org/x/net"
  revision = "1c05540f6879653db88113bc4a2b70aec4bd491f"

[[constraint]]
  name = "golang.org/x/text"
  revision = "b19bf474d317b857955b12035d2c5acb57ce8b01"

[[constraint]]
  name = "k8s.io/gengo"
  revision = "9e661e9308f078838e266cca1c673922088c0ea4"

[[constraint]]
  name = "k8s.io/kube-openapi"
  revision = "868f2f29720b192240e18284659231b440f9cda5"
